Create new design block
WeDevelop-ARG/full-stack-beginner-program pull request #11
Opened 2020-12-21 12:38 UTC by roke77

2020-12-21 12:49 UTC, abelosorio reviewed
So far so good.

2020-12-21 13:58 UTC, nahudalla requested changes

2020-12-21 13:58 UTC, nahudalla commented on content/block-2/index.md
> +### Github ??? (maybe a better title like: Collaboration)
```suggestion
### Git Flow in practice
```

2020-12-21 13:58 UTC, nahudalla commented on content/block-2/index.md
> +- TODO: How to create a Pull Request: https://
```suggestion
- How to create a Pull Request: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
```

2020-12-21 13:58 UTC, nahudalla commented on content/block-2/index.md
> +2. Create a new Pull Request extracting components into its own files (TODO: FE Arch ???) and converting React Class Components into Functional Components.
FE architecture is not the focus of this block. They'll be doing that in B4.
```suggestion
2. Create a new Pull Request extracting components into its own files and converting React Class Components into Functional Components.
```

2020-12-21 13:58 UTC, nahudalla commented on content/block-3/index.md
> +- Advanced CSS
🤔 the focus of this block should be only `Component Diagrams` and `Team Collaboration`. CSS and FE Architecture is Block 4.

2021-01-12 14:30 UTC, MPucheta approved these changes

2021-01-12 14:45 UTC, nahudalla approved these changes

2021-01-12 14:46 UTC, merged